case:
	del /q src\test\solutions\*
	del /q src\test\testcases\*

target:
	del /q target\*

cls:
	del /q src\main\mt22\parser\.antlr
	del /q src\main\mt22\parser\MT22.interp
	del /q src\main\mt22\parser\MT22.tokens
	del /q src\main\mt22\parser\MT22Lexer.interp
	del /q src\main\mt22\parser\MT22Lexer.tokens
	del /q src\main\mt22\parser\MT22Lexer.py
	del /q src\main\mt22\parser\MT22Parser.py
	del /q src\main\mt22\parser\MT22Visitor.py

cache:
	del /q src\main\mt22\astgen\__pycache__
	del /q src\main\mt22\parser\__pycache__
	del /q src\test\__pycache__